## Static
## 1. Microwave
#microwave:
#  model_id: 7310
#  scale: 1.0
#  joint_indices: [0]
#  joint_limits: [[45, 45], ]
#
## 2. Bucket
#bucket:
#  model_id: 102352
#  scale: 1.0
#  joint_indices: [0]
#  joint_limits: [[90, 90], ]
#
## 3. Trashcan
#trashcan:
#  model_id: 11818
#  scale: 1.0
#  joint_indices: [ 0 ]
#  joint_limits: [ [ 0, 0 ], ]
#
## 4. Fan
#fan:
#  model_id: 101375
#  scale: 1.0
#  joint_indices: [ 0 ]
#  joint_limits: [ [ 0, 0 ], ]
#
## 5. Globe
#globe:
#  model_id: 100736
#  scale: 1.0
#  joint_indices: [ 0 ]
#  joint_limits: [ [ 0, 0 ], ]
#
## 6. USB
#usb:
#  model_id: 100061
#  scale: 1.0
#  joint_indices: [0]
#  joint_limits: [[-0.132, -0.132], ]




# Mobility
# A1. Microwave
microwave:
  model_id: 7310
  scale: 1.0

# A2. Bucket
bucket:
  model_id: 102352
  scale: 1.0

# A3. Trashcan
trashcan:
  model_id: 11818
  scale: 1.0

# A4. Fan
fan:
  model_id: 101375
  scale: 1.0

# A5. Globe
globe:
  model_id: 100736
  scale: 1.0

# A6. USB
usb:
  model_id: 100061
  scale: 1.0

# B1. Toilet

# B2. Faucet

# B3. Folding Chair

# B4. Box

# B5. Refrigerator

# B6. Toaster
