# Cat 2 Static
# B1. Toilet
toilet:
  model_id: 102621
  scale: 1.0
  joint_names: ['joint_0', 'joint_1', 'joint_2', 'joint_3']
  joint_limits: [[0, 0], [60, 60], [30, 30], [0, 0]]

# B2. Faucet
faucet:
 model_id: 167
 scale: 1.0
 joint_names: ['joint_0', 'joint_1', 'joint_3']
 joint_limits: [[0, 0], [0, 0], [0, 0] ]

# B3. Folding Chair
folding_chair:
  model_id: 100557
  scale: 1.0
  joint_names: ['joint_0', 'joint_2' ]
  joint_limits: [[ 0, 0 ], [0, 0]]

# B4. Box
box:
  model_id: 100162
  scale: 1.0
  joint_names: ['joint_0', 'joint_1', 'joint_2', 'joint_3']
  joint_limits: [ [ 0, 0 ], [ 0, 0 ], [ 0, 0 ], [ 0, 0 ] ]

# B5. Refrigerator
refrigerator:
  model_id: 10655
  scale: 1.0
  joint_names: ['joint_1', 'joint_2']
  joint_limits: [ [45, 45], [45, 45] ]

# B6. Toaster
toaster:
  model_id: 103482
  scale: 1.0
  joint_names: ['joint_0', 'joint_1']
  joint_limits: [[0, 0], [0, 0]]
