## Mobility
# 1. Microwave
microwave:
  model_id: 7310
  scale: 1.0

# 2. Bucket
bucket:
  model_id: 102352
  scale: 1.0

# 3. Trashcan
trashcan:
  model_id: 11818
  scale: 1.0

# 4. Fan
fan:
  model_id: 101375
  scale: 1.0

# 5. Globe
globe:
  model_id: 100736
  scale: 1.0

# 6. USB
usb:
  model_id: 100061
  scale: 1.0

# 7. USB
vault:
  model_id: 100061
  scale: 1.0